# Generated by Django 4.1.7 on 2023-12-25 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toursim_app', '0002_state_alter_heritagesite_image_alter_place_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=255)),
                ('city_description', models.TextField()),
                ('city_videos', models.FileField(blank=True, null=True, upload_to='Media/City/')),
                ('city_image', models.ImageField(upload_to='images/Cities/')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/Gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='State_details',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_image', models.ImageField(upload_to='images/States/')),
                ('state_name', models.CharField(max_length=255)),
                ('state_description', models.TextField()),
                ('state_video', models.FileField(blank=True, null=True, upload_to='Media/State/')),
            ],
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AddField(
            model_name='gallery',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toursim_app.state_details'),
        ),
        migrations.AddField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toursim_app.state_details'),
        ),
    ]
