# Generated by Django 4.1.7 on 2023-12-25 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toursim_app', '0003_city_gallery_state_details_delete_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_image', models.ImageField(upload_to='images/location/')),
                ('location_videos', models.FileField(blank=True, null=True, upload_to='Media/Location/')),
                ('location_description', models.TextField()),
                ('location_name', models.CharField(max_length=255)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toursim_app.city')),
            ],
        ),
    ]
